### ISSUE TITLE
Custom welcome message

### ISSUE THREAD

**Issue by scriptzteam** [ovpn-to/oVPN.to-nntp2nntp#2]
Is it possible to add custom welcome message? or replace the one which gives original nntp server?

**Comment by ovpn-to** [comment]
see crc-error commit. you'll find a banner there.

**Comment by scriptzteam** [comment]
Okay  know how to write own message but how to replace the original server message like "200 Welcome to astraweb blahbla"

is there an function i can use to replace the words?

**Comment by ovpn-to** [comment]
def lineReceived(self, line):
-    if (line.startswith('200') or line.startswith('201')):
-      self.server.sendLine('201 oVPN.to NNTP-Proxy Ready, posting not allowed')
