### ISSUE TITLE
Upload example xxxnntp_.php

### ISSUE THREAD

**Issue by extremeshok** [ovpn-to/oVPN.to-nntp2nntp#3]
Accoridng to the source code, there appears to be some sort of user statistic tracker.

Could you please post an example xxxnntp.php

```
url = "https://vcp.ovpn.to/xxxnntp_.php"
    values = {'user' : self.auth_user, 'duration' : self.duration, 'downloaded' : self.downloaded_bytes, 'uploaded' : self.uploaded_bytes, 'port' : SERVER_PHONEPORT }
    try:
      r = requests.post(url,data=values)
```

**Comment by ovpn-to** [comment]
send a post with user, duration, downloaded_bytes, uploaded_bytes, port and put it to mysql. 
guess, no example needed. basic php/mysql.
