### ISSUE TITLE
config failed

### ISSUE THREAD

**Issue by ovpn-to** [ovpn-to/oVPN.to-nntp2nntp#7]
error message:

python2.7 nntp_proxy.py cfg.cfg
> 1500720865.38:  CONFIG failed, exception = 'invalid literal for int()
> with base 10: '11119                # set listen port''
> 1500720865.38:  LOGFILE failed, exception = ''bool' object has no
> attribute '__getitem__''
> sys.platform = 'linux2'
> 1500720865.46:  Factory or Reactor failed, exception = ''bool' object
> has no attribute '__getitem__''

solution: remove all comments from config, everything behind (including) #

**Comment by scriptzteam** [comment]
And also how to add nntp providers?

**Comment by ovpn-to** [comment]
mysql?
